config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :shoes
  root 'home#page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  belongs_to :profile
end

app/models/buyers_seller.rb
class BuyersSeller < ApplicationRecord
  belongs_to :buyer
  belongs_to :seller
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :profile
  has_many :shoes
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :seller
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  has_one :buyer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to shoes_url, notice: 'Shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:brand, :picture, :price, :release_date, :description, :size, :seller_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/home/page.html.erb
<body>
  <div class="container">
      <%= render 'partials/navbar'%>    
      <%= yield %>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SideProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">GOAT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item ">
        <a class="nav-link" href="#">Shop All <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Collections</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#">Styles</a>
      </li>

      <li class="nav-item">
          <a class="nav-link" href="#">Brands</a>
      </li>
      
      
      
    </ul>
    
  </div>
</nav>

app/views/shoes/_form.html.erb
<%= form_with(model: shoe, local: true) do |form| %>
  <% if shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :seller_id %>
    <%= form.text_field :seller_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shoes/edit.html.erb
<h1>Editing Shoe</h1>

<%= render 'form', shoe: @shoe %>

<%= link_to 'Show', @shoe %> |
<%= link_to 'Back', shoes_path %>

app/views/shoes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shoes</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Picture</th>
      <th>Price</th>
      <th>Release date</th>
      <th>Description</th>
      <th>Size</th>
      <th>Seller</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shoes.each do |shoe| %>
      <tr>
        <td><%= shoe.brand %></td>
        <td><%= shoe.picture %></td>
        <td><%= shoe.price %></td>
        <td><%= shoe.release_date %></td>
        <td><%= shoe.description %></td>
        <td><%= shoe.size %></td>
        <td><%= shoe.seller %></td>
        <td><%= link_to 'Show', shoe %></td>
        <td><%= link_to 'Edit', edit_shoe_path(shoe) %></td>
        <td><%= link_to 'Destroy', shoe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shoe', new_shoe_path %>

app/views/shoes/new.html.erb
<h1>New Shoe</h1>

<%= render 'form', shoe: @shoe %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @shoe.brand %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @shoe.picture %>
</p>

<p>
  <strong>Price:</strong>
  <%= @shoe.price %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @shoe.release_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shoe.description %>
</p>

<p>
  <strong>Size:</strong>
  <%= @shoe.size %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @shoe.seller %>
</p>

<%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<%= link_to 'Back', shoes_path %>